language: ruby

rvm:
  - 2.3.1
  - 2.2.5
  - ruby-head
  - rbx-2
  - jruby

matrix:
  include:
    - rvm: "2.2"
      env: TEST_SUITE=test:templates

env:
  global:
    - JRUBY_OPTS=--dev
  matrix:
    - TEST_SUITE=test

script:
  - bundle exec rake ${TEST_SUITE:}

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby
