language: ruby

rvm:
  - 2.2.3
  - ruby-head
  - rbx-2
  - jruby

gemfile:
  - Gemfile

env:
  global:
    - JRUBY_OPTS=--dev
    - TEST_SUITE=test

sudo: false

before_script:
  - RAILS_ENV=test bundle exec rake --rakefile=test/dummy/Rakefile db:setup

script:
  - bundle exec rake ${TEST_SUITE}

matrix:
  include:
    - env: TEST_SUITE=test:templates
      gemfile: Gemfile
      rvm: 2.2.3
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby
