language: ruby

rvm:
  - 2.2.3
  - ruby-head
  - rbx-2
  - jruby

env:
  global:
    - JRUBY_OPTS=--dev

sudo: false

cache: bundler

before_script:
  - RAILS_ENV=test bundle exec rake --rakefile=test/dummy/Rakefile db:setup

script:
  - bundle exec rake ${TEST_SUITE:-test}

matrix:
  include:
    - env: TEST_SUITE=test:templates
      rvm: 2.2.3
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby
